// POS V14
let products=JSON.parse(localStorage.getItem('products')||'[]'),sales=JSON.parse(localStorage.getItem('sales')||'[]'),categories=JSON.parse(localStorage.getItem('categories')||'[]'),cart=[],currentCategory='All',editingID=null,scannerRunning=false,scanLocked=false,selectedBarcodes=[],barcodeCopies={};
const money=n=>Number(n||0).toFixed(2), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function saveData(){localStorage.setItem('products',JSON.stringify(products));localStorage.setItem('sales',JSON.stringify(sales));localStorage.setItem('categories',JSON.stringify(categories))}
products=products.map(p=>{p.categories=Array.isArray(p.categories)?p.categories:(p.category?[p.category]:[]);p.variants=Array.isArray(p.variants)?p.variants:[];p.bundles=Array.isArray(p.bundles)?p.bundles:[];return p});saveData();
const vars=p=>p.variants||[], sized=p=>vars(p).length>0, cats=p=>Array.isArray(p.categories)?p.categories:(p.category?[p.category]:[]);
function opt(p,k){if(k!=='base'){let v=vars(p).find(x=>String(x.id)===String(k));if(v)return v}return{id:'base',name:'',price:Number(p.price||0),stock:Number(p.stock||0),barcode:String(p.barcode||'')}}
function getStock(p,k){return Number(opt(p,k).stock||0)}function setStock(p,k,n){n=Math.max(0,Number(n||0));if(k==='base')p.stock=n;else{let v=vars(p).find(x=>String(x.id)===String(k));if(v)v.stock=n}}
function lineTotal(i){let p=products.find(x=>x.id===i.productId),q=Number(i.qty),base=Number(i.price);if(!p||!p.bundles.length)return base*q;let best=base*q;p.bundles.forEach(b=>{let n=Math.max(2,Number(b.qty)),bp=Number(b.price),v=Math.floor(q/n)*bp+(q%n)*base;if(v<best)best=v});return best}function totalCart(){return cart.reduce((t,i)=>t+lineTotal(i),0)}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(page)?.classList.add('active');if(page==='dashboard')updateDashboard();if(page==='checkout'){displayProducts();displayCategoryButtons();updateCart()}if(page==='inventory')displayInventory();if(page==='barcodes')displayBarcodeList();if(page==='sales')displaySales();if(page==='categories')displayCategories()}
function setupButtons(){document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.getElementById('clearCart')?.addEventListener('click',clearCart);document.getElementById('cashPay')?.addEventListener('click',()=>pay('Cash'));document.getElementById('cardPay')?.addEventListener('click',()=>pay('Card'));document.getElementById('generateBarcode')?.addEventListener('click',generateProductBarcode);document.getElementById('saveProduct')?.addEventListener('click',saveProduct);document.getElementById('updateProduct')?.addEventListener('click',updateProduct);document.getElementById('addCategory')?.addEventListener('click',addCategory);document.getElementById('clearSales')?.addEventListener('click',clearSales);document.getElementById('startCamera')?.addEventListener('click',startScanner);document.getElementById('stopCamera')?.addEventListener('click',stopScanner);document.getElementById('selectAllBarcodes')?.addEventListener('click',selectAllBarcodes);document.getElementById('clearBarcodeSelection')?.addEventListener('click',clearBarcodeSelection);document.getElementById('printSelected')?.addEventListener('click',printSelectedBarcodes);document.getElementById('printAll')?.addEventListener('click',printAllBarcodes)}
function updateDashboard(){let a=document.getElementById('productCount');if(a)a.innerText=products.length;let n=products.reduce((t,p)=>t+(sized(p)?vars(p).reduce((x,v)=>x+Number(v.stock||0),0):Number(p.stock||0)),0),b=document.getElementById('inventoryCount');if(b)b.innerText=n;let l=products.filter(p=>sized(p)?vars(p).some(v=>v.stock<=2):p.stock<=2),c=document.getElementById('lowStock');if(c)c.innerText=l.length;let d=document.getElementById('itemsSold');if(d)d.innerText=sales.reduce((t,s)=>t+(s.items||[]).reduce((x,i)=>x+Number(i.qty||0),0),0);let box=document.getElementById('lowStockList');if(box)box.innerHTML=l.map(p=>`<div class="sales-item">⚠️ ${esc(p.name)}<br>${sized(p)?vars(p).map(v=>`${esc(v.name)}: ${v.stock}`).join(' · '):`Stock: ${p.stock}`}</div>`).join('')||'No low-stock items';displayBestSellers()}
function displayBestSellers(){let x=document.getElementById('bestSellers');if(!x)return;let t={};sales.forEach(s=>(s.items||[]).forEach(i=>t[i.name]=(t[i.name]||0)+Number(i.qty||0)));x.innerHTML=Object.entries(t).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,q])=>`<div class="sales-item">⭐ ${esc(n)} — ${q} sold</div>`).join('')||'No sales yet'}
function generateBarcodeNumber(){let c=String(Date.now()).slice(-12);while(products.some(p=>String(p.barcode)===c)||products.some(p=>vars(p).some(v=>String(v.barcode)===c)))c=String(Number(c)+1).slice(-12);return c}
function generateProductBarcode(){let e=document.getElementById('productBarcode');if(e)e.value=generateBarcodeNumber()}
function generateVariantBarcode(button){let row=button?.closest('.variant-row');let input=row?.querySelector('.variant-barcode');if(input)input.value=generateBarcodeNumber()}
function buildExtraUI(){let add=document.getElementById('addProduct');if(add&&!document.getElementById('productCategories')){add.insertAdjacentHTML('beforeend',`<h3>Categories</h3><div id="productCategories"></div><h3>Optional Size Variants</h3><p>Leave empty for a normal product.</p><div id="productVariants"></div><button type="button" onclick="addVariantRow('product')">Add Size Variant</button><h3>Optional Bundles / Deals</h3><p>Example: 3 for $5.</p><div id="productBundles"></div><button type="button" onclick="addBundleRow('product')">Add Bundle</button>`)}let edit=document.getElementById('editProduct');if(edit&&!document.getElementById('editCategories')){edit.insertAdjacentHTML('beforeend',`<h3>Categories</h3><div id="editCategories"></div><h3>Optional Size Variants</h3><div id="editVariants"></div><button type="button" onclick="addVariantRow('edit')">Add Size Variant</button><h3>Bundles / Deals</h3><div id="editBundles"></div><button type="button" onclick="addBundleRow('edit')">Add Bundle</button>`)}let salesBox=document.getElementById('sales');if(salesBox&&!document.getElementById('undoSale')){let b=document.createElement('button');b.id='undoSale';b.textContent='↩️ Undo Last Sale';b.onclick=undoLastSale;salesBox.insertBefore(b,salesBox.firstChild)}}
function categoryChecks(prefix,selected=[]){let x=document.getElementById(prefix+'Categories');if(!x)return;x.innerHTML=categories.map(c=>`<label style="display:inline-block;margin:5px"><input type="checkbox" value="${esc(c)}" ${selected.includes(c)?'checked':''}> ${esc(c)}</label>`).join('')||'No categories yet'}function checkedCats(prefix){return [...document.querySelectorAll(`#${prefix}Categories input:checked`)].map(x=>x.value)}
function addVariantRow(prefix,v={}){let x=document.getElementById(prefix+'Variants');if(!x)return;let r=document.createElement('div');r.className='variant-row';r.style='border:1px solid #ddd;padding:8px;margin:6px 0;border-radius:8px';r.innerHTML=`<input class="variant-name" placeholder="Size name" value="${esc(v.name||'')}"><input class="variant-price" type="number" step="0.01" placeholder="Price" value="${v.price??''}"><input class="variant-stock" type="number" min="0" placeholder="Stock" value="${v.stock??0}"><div style="display:flex;gap:6px;align-items:center"><input class="variant-barcode" placeholder="Barcode" value="${esc(v.barcode||'')}" style="flex:1"><button type="button" onclick="generateVariantBarcode(this)">Generate Barcode</button></div><button type="button" onclick="this.parentElement.remove()">Remove</button>`;x.appendChild(r)}
function readVariants(prefix){return [...document.querySelectorAll(`#${prefix}Variants .variant-row`)].map(r=>({id:r.dataset.variantId||String(Date.now()+Math.random()),name:r.querySelector('.variant-name')?.value.trim(),price:Number(r.querySelector('.variant-price')?.value||0),stock:Math.max(0,Number(r.querySelector('.variant-stock')?.value||0)),barcode:r.querySelector('.variant-barcode')?.value.trim()||generateBarcodeNumber()})).filter(v=>v.name)}
function addBundleRow(prefix){let x=document.getElementById(prefix+'Bundles');if(!x)return;let r=document.createElement('div');r.className='bundle-row';r.style='display:flex;gap:6px;margin:6px 0';r.innerHTML='<input class="bundle-qty" type="number" min="2" value="2" placeholder="Qty"><input class="bundle-price" type="number" min="0" step="0.01" placeholder="Bundle price"><button type="button" onclick="this.parentElement.remove()">Remove</button>';x.appendChild(r)}function readBundles(prefix){return [...document.querySelectorAll(`#${prefix}Bundles .bundle-row`)].map(r=>({qty:Math.max(2,Number(r.querySelector('.bundle-qty')?.value||0)),price:Math.max(0,Number(r.querySelector('.bundle-price')?.value||0))})).filter(b=>b.qty>=2)}
function saveProduct(){let name=document.getElementById('productName')?.value.trim();if(!name){alert('Enter a product name.');return}let v=readVariants('product'),p={id:Date.now(),name,price:Number(document.getElementById('productPrice')?.value||0),stock:Math.max(0,Number(document.getElementById('productStock')?.value||0)),categories:checkedCats('product'),barcode:document.getElementById('productBarcode')?.value.trim()||'',image:'',variants:v,bundles:readBundles('product')};if(v.length){p.price=0;p.stock=0;p.barcode=''}p.category=p.categories[0]||'';let f=document.getElementById('productImage')?.files?.[0],done=()=>{products.push(p);saveData();updateDashboard();displayInventory();displayProducts();showPage('inventory')};if(f){let r=new FileReader();r.onload=e=>{p.image=e.target.result;done()};r.readAsDataURL(f)}else done()}
function displayInventory(){let x=document.getElementById('inventoryList');if(!x)return;x.innerHTML=products.map(p=>`<div class="inventory-item">${p.image?`<img src="${p.image}">`:'📦'}<h3>${esc(p.name)}</h3>Categories: ${cats(p).map(esc).join(', ')||'None'}<br>${sized(p)?vars(p).map(v=>`${esc(v.name)} — $${money(v.price)} — Stock ${v.stock} — ${esc(v.barcode)}`).join('<br>'):`Price: $${money(p.price)}<br>Stock: ${p.stock}<br>Barcode: ${esc(p.barcode)}`}<br>${p.bundles.length?'🏷 '+p.bundles.map(b=>`${b.qty} for $${money(b.price)}`).join(' | '):''}<br><br><button onclick="editProduct(${p.id})">✏️ Edit</button><button onclick="addStock(${p.id})">+1</button><button onclick="removeStock(${p.id})">-1</button><button onclick="deleteProduct(${p.id})">🗑 Delete</button></div>`).join('')}
function addStock(id){let p=products.find(x=>x.id===id);if(p){let k=sized(p)?String(vars(p)[0].id):'base';setStock(p,k,getStock(p,k)+1);saveData();displayInventory();updateDashboard()}}function removeStock(id){let p=products.find(x=>x.id===id);if(p){let k=sized(p)?String(vars(p)[0].id):'base';setStock(p,k,getStock(p,k)-1);saveData();displayInventory();updateDashboard()}}function deleteProduct(id){products=products.filter(p=>p.id!==id);saveData();displayInventory();displayProducts();updateDashboard()}
function editProduct(id){let p=products.find(x=>x.id===id);if(!p)return;editingID=id;document.getElementById('editName').value=p.name;document.getElementById('editPrice').value=p.price;document.getElementById('editStock').value=p.stock;categoryChecks('edit',cats(p));let v=document.getElementById('editVariants');if(v){v.innerHTML='';vars(p).forEach(x=>{addVariantRow('edit',x);let r=v.lastElementChild;r.dataset.variantId=x.id})}let b=document.getElementById('editBundles');if(b){b.innerHTML='';(p.bundles||[]).forEach(z=>{addBundleRow('edit');b.lastElementChild.querySelector('.bundle-qty').value=z.qty;b.lastElementChild.querySelector('.bundle-price').value=z.price})}showPage('editProduct')}
function updateProduct(){let p=products.find(x=>x.id===editingID);if(!p)return;let v=readVariants('edit');p.name=document.getElementById('editName').value.trim();p.categories=checkedCats('edit');p.category=p.categories[0]||'';p.bundles=readBundles('edit');if(v.length){p.variants=v;p.price=0;p.stock=0;p.barcode=''}else{p.variants=[];p.price=Number(document.getElementById('editPrice').value||0);p.stock=Math.max(0,Number(document.getElementById('editStock').value||0))}saveData();displayInventory();displayProducts();updateDashboard();showPage('inventory')}
function addCategory(){let i=document.getElementById('categoryName'),n=i?.value.trim();if(!n)return;if(!categories.includes(n))categories.push(n);saveData();i.value='';displayCategories();categoryChecks('product',[]);displayCategoryButtons()}function displayCategories(){let x=document.getElementById('categoryList');if(x)x.innerHTML=categories.map((c,i)=>`<div class="category-card">${esc(c)} <button onclick="deleteCategory(${i})">Delete</button></div>`).join('')}function deleteCategory(i){let c=categories[i];products.forEach(p=>{p.categories=cats(p).filter(x=>x!==c);p.category=p.categories[0]||''});categories.splice(i,1);saveData();displayCategories();categoryChecks('product',[]);displayCategoryButtons()}
function displayCategoryButtons(){let x=document.getElementById('categoryButtons');if(x)x.innerHTML='<button onclick="filterCategory(\'All\')">All</button>'+categories.map(c=>`<button onclick='filterCategory(${JSON.stringify(c)})'>${esc(c)}</button>`).join('')}function filterCategory(c){currentCategory=c;displayProducts()}
function chooseVariant(id){let p=products.find(x=>x.id===id);if(!p)return;if(!sized(p)){addToCart(id,'base');return}let m=document.createElement('div');m.id='variantModal';m.style='position:fixed;inset:0;background:#000a;display:flex;align-items:center;justify-content:center;z-index:9999;padding:20px';m.innerHTML=`<div style="background:#fff;color:#000;padding:20px;border-radius:16px;width:min(420px,100%)"><h2>${esc(p.name)}</h2>${vars(p).map(v=>`<button style="display:block;width:100%;margin:8px 0;padding:14px" onclick="addToCart(${p.id},'${v.id}');document.getElementById('variantModal').remove()">${esc(v.name)} — $${money(v.price)} — Stock ${v.stock}</button>`).join('')}<button style="width:100%;padding:12px" onclick="this.closest('#variantModal').remove()">Cancel</button></div>`;document.body.appendChild(m)}
function displayProducts(){let x=document.getElementById('products');if(!x)return;x.innerHTML=products.filter(p=>currentCategory==='All'||cats(p).includes(currentCategory)).map(p=>`<div class="product" onclick="chooseVariant(${p.id})">${p.image?`<img src="${p.image}">`:'📦'}<h3>${esc(p.name)}</h3><p>${sized(p)?'From ':''}$${money(sized(p)?Math.min(...vars(p).map(v=>v.price)):p.price)}</p><small>${sized(p)?vars(p).map(v=>`${esc(v.name)}: ${v.stock}`).join(' · '):`Stock: ${p.stock}`}</small>${p.bundles.length?`<br><small>🏷 ${p.bundles.map(b=>`${b.qty} for $${money(b.price)}`).join(' · ')}</small>`:''}</div>`).join('')}
function addToCart(id,k='base'){let p=products.find(x=>x.id===id);if(!p)return;let o=opt(p,k),i=cart.find(x=>x.productId===id&&String(x.variantKey)===String(k));if((i?.qty||0)>=o.stock){alert('Not enough stock.');return}if(i)i.qty++;else cart.push({productId:id,variantKey:String(k),name:o.name?`${p.name} — ${o.name}`:p.name,price:Number(o.price),qty:1});updateCart()}
